### ISSUE TITLE
[Linear] Add notifications links for issues and projects

### ISSUE THREAD

**Issue by termosa** [raycast/extensions#10920]
### Extension

https://www.raycast.com/linear/linear

### Description

When pressing [⌘][⏎] it opens list of notifications and not the selected one.

### Steps To Reproduce

1. Open Linear Notifications
2. Hit [⌘][⏎]
3. Check if you can see the selected notification content

**Comment by thomaslombart** [comment]
Yes, this is expected. What do you suggest using?

**Comment by termosa** [comment]
@thomaslombart

Every time I navigate to the Inbox from Linear extension I feel like I have to start my Inbox processing from scratch, even the order of notifications is different, so I just start from the first one on the web and stop using the extension.

I've checked it and now I see that you cannot focus the specific notification via URL when opening the page.
At least to me, it would make more sense if Open in Browser would navigate to the ticket that has been changed, to the comment that has been added.

**Comment by termosa** [comment]
While we are here, I also want to add that search by secondary text doesn't work.
So I cannot search by ticket title or ticket number.

**Comment by thomaslombart** [comment]
@termosa I agree these would be good improvements but we're unfortunately limited by [Linear's API](https://studio.apollographql.com/public/Linear-API/variant/current/schema/reference/interfaces/Notification?query=notifications) here. Feel free to reach out on their [Slack community](https://app.slack.com/client/TM567NELB/threads) to ask support for that.

**Comment by thomaslombart** [comment]
> So I cannot search by ticket title or ticket number.

This has been fixed (#11041).

**Comment by termosa** [comment]
@thomaslombart Thank you!

> This has been fixed (https://github.com/raycast/extensions/pull/11041).
 I see that last update of Linear ticket was the same day you wrote the comment, but I am still not able to search notifications by the ticket title
![CleanShot 2024-03-06 at 19 06 52@2x](https://github.com/raycast/extensions/assets/494013/255b1ab9-4be9-4f1a-b180-7bfcc116e04b)

**Comment by thomaslombart** [comment]
So, I will mark this issue as "not planned" as we are limited by Linear. Thank you for your feedback! Don't hesitate to reopen it if it becomes technically possible.

**Comment by termosa** [comment]
I'm trying to rich them about API 👌

**Comment by termosa** [comment]
@thomaslombart I have asked it on their [Slack channel](https://linearcustomers.slack.com/archives/CN61HRZ9T/p1709796782850359), and they directed me to this path: `IssueNotification.comment.url`. It won't open every activity, but will at least scroll to the comment.

**Comment by thomaslombart** [comment]
Interesting. We can probably use some improvements here. Here's what I'm thinking of:

- Make the `Open Inbox` action a regular one (and not the secondary one) and update the keyboard shortcut to `⌘` +`O`
- Add a new secondary action specifically for issues to open the comment URL.

**Comment by termosa** [comment]
@thomaslombart I see this super beneficial for Notifications screen.

Enter - Mark as Read
Cmd + Enter - open web as close as possible (comment or ticket at least)

I really would not care about opening Inbox with the hotkey in this menu. It is so generic (and not used by me with Raycast Linear Menu and Notifications) that I can create QuickLink if needed or have it as a 4-buttons hotkey in the Notifications menu. 

P.S. You may want to do the same update in the OSX Menu (top screen counter) as well, so it opens the specific comment. 

P.P.S. Also, I will suggest Linear to have links available for all ticket events like Priority Changed, Assigned, and so on. Would be nice to see them highlighted when opening link from anywhere.
