### ISSUE TITLE
[Window Manager] Next / Previous Desktop broken - window is not moved

### ISSUE THREAD

**Issue by jaykobo** [raycast/extensions#14451]
### Extension

https://www.raycast.com/extensions/window-management

### Raycast Version

1.82.5

### macOS Version

13.6.9

### Description

As the description for "Next Desktop" says "Move focused window to next desktop." I want to move my focused window to the next (or previous) desktop. Which is currently not working.

I am pretty sure that it was working before approximately version 1.75.0 or so, where the Window Management gets more functionality and "Custom Window Management Commands". Can't test this, because I can not roll back or install earlier versions of raycast.

![window-management](https://github.com/user-attachments/assets/6b831085-8c93-44ec-b62e-c10489d7b2dc)

### Steps To Reproduce

1. I have one monitor and several (virtual) desktops on it
2. I have a window focused and open with CMD + SPACE raycast
3. I choose "Next Desktop" (from Window Management) and hit Enter

### Current Behaviour

My (virtual) desktop changes, but the window was not moved to the next desktop
_(Same behaviour for "Previous Desktop")_

### Expected Behaviour

My (virtual) desktop changes, AND the window was moved to the next desktop

**Comment by motionbluur** [comment]
I'm also having the same issue. Updated to MacOS Sequoia and noticed the issue.

**Comment by austinm911** [comment]
I'm having this issue too. I have to turn the Next Window command off and on to get it working again

**Comment by jaykobo** [comment]
> I'm having this issue too. I have to turn the Next Window command off and on to get it working again

I tried that, but it didn't work. I also tried to add another hotkey, but that didn't work either.

**Comment by sgoridotla1** [comment]
Bump. I'm having this issue too. 
When using Next Desktop or Previous Desktop the desktop changes but the window is no longer moved, it stays on the desktop it was. 

Hotkeys
Next desktop: Control + Option + . 
Prev desktop: Control + Option + ,

Raycast Version: 1.83.1
macOS Version: Sequoia 15.0

**Comment by adamhl8** [comment]
Also having the same issue with Next/Previous Desktop. The desktop switches but the window doesn't move.

On Sequoia 15.0

**Comment by RichDom2185** [comment]
I updated to macOS Sequoia 15.0.1 and also having this issue. Seems like the macOS 15 update broke moving to next/previous spaces for not just Raycast but also other window management tools.

**Comment by MarkusLanger** [comment]
any news?

**Comment by MarkusLanger** [comment]
It is still a problem.

**Comment by jaykobo** [comment]
Right. This issue still exists and is not fixed yet!

**Comment by albertxwz** [comment]
I have implemented an extension to move windows between spaces. This is to simulate the action "drag the window and switch spaces". #15367

**Comment by jaykobo** [comment]
As the changelog for v1.87.0 states the fix has unfortunately only been implemented for Sequoia. The error still exists for me on ventura.

**Comment by pernielsentikaer** [comment]
Is this happening for all windows or only some?

**Comment by pernielsentikaer** [comment]
![Raycast05122024-3k1IYOVp png@2x](https://github.com/user-attachments/assets/a6d943ca-60f6-4944-aa9b-c652325401d3)


I just tested this on a clean installation of macOS 13.6 and I can't reproduce the issue

**Comment by jaykobo** [comment]
Hey, thanks for you fast reply!
By now I am running Ventura 13.7.1 (updated the first comment) - it still occurs and its happening for all windows.

![macbook](https://github.com/user-attachments/assets/63783f22-3610-44fe-9bd1-a50a26dd47c0)

**Comment by pernielsentikaer** [comment]
That sounds like a macOS issue. Did you give Raycast accessibility rights in Settings?

**Comment by jaykobo** [comment]
Sure I did. It is checked in Privacy & Security > Accessibility. And it worked perfectly until version 1.75.0 (approximately).

![system-settings](https://github.com/user-attachments/assets/0948eceb-d12f-4f74-aeee-adf5bcacf858)

**Comment by monsterhxw** [comment]
> Hey, thanks for you fast reply!
> 
> By now I am running Ventura 13.7.1 (updated the first comment) - it still occurs and its happening for all windows.
> 
> 
> 
> ![macbook](https://github.com/user-attachments/assets/63783f22-3610-44fe-9bd1-a50a26dd47c0)
> 
> 

I have the same issue.

**Comment by caspardue** [comment]
The recent update fixed the issue for me, but for some reason the functionality is still not working for JetBrains applications (Rider and DataGrip in my case). I can open a separate issue if needed?

**Comment by xxxzsgxxx** [comment]
I have the same issue. 
macos 13.7.8 , raycast 1.103.3

**Comment by jaykobo** [comment]
As an update from me: It's working again for me now. Meanwhile I am on MacOS 15.6.1 (Sequoia). Unfortunately, I can't say for sure what fixed it, but it was probably one of the latest updates.

**Comment by uhkeller** [comment]
Edit: Working again in Raycast 1.104.13.
And broken again, I think after updating to macOS 26.4, or 26.4.1. Raycast 1.104.12.

**Comment by gpessia** [comment]
R: Version 0.71.3.0 (0)
MOS: 26.5.2 
even moving through spaces doesn't work
