### ISSUE TITLE
[Terminal Shop] Extension crashes when proceeding the order

### ISSUE THREAD

**Issue by mattisssa** [raycast/extensions#18151]
### Extension

https://www.raycast.com/terminaldotshop/terminaldotshop

### Raycast Version

1.94.2

### macOS Version

15.3.2

#### Screencast:

https://github.com/user-attachments/assets/e10a4262-d72d-499d-9859-df214a06585b

Let me know if you need more info.

#### Error:
```
Error: 400 This product cannot be purchased.

t.generate:error.ts:60:13

---
57:     const error = errorResponse as Record<string, any>;
58: 
59:     if (status === 400) {
60:       return new BadRequestError(status, error, message, headers);
61:     }
62: 
63:     if (status === 401) {
---

$.makeStatusError:terminaldotshop.js:38:9381
$.makeRequest:terminaldotshop.js:38:10312
```

### Steps To Reproduce

1. Select product
2. Provide address & payment card
3. Proceed to the purchase

### Current Behaviour

The extension crashes

**Comment by pernielsentikaer** [comment]
Should be fixed, please run "Check for Extension Updates" and try again 😊

**Comment by mattisssa** [comment]
Hey @pernielsentikaer 
Are you sure you've deployed the extension? I ran the command a couple of times and it seems my extension is up to date, but it still doesn't work.

Last update was 

![Image](https://github.com/user-attachments/assets/6a945c75-c8ae-4986-8892-10d0c48d1452)

**Comment by pernielsentikaer** [comment]
Checking with @thdxr

**Comment by ichikmarev** [comment]
I am experiencing the same issue with the latest updates of the extension and Raycast
