### ISSUE TITLE
fatal: Not possible to fast-forward, aborting

### ISSUE THREAD

**Issue by koaladlt** [raycast/extensions#18584]
### Description

Hi Raycast team 👋

I'm trying to update an extension, but I run into an issue when running `@raycast/api@latest pull-contributions`

error  - pulling new contributions
failed running git Command failed: git pull origin ext/dolar-cripto-ar --ff-only
From https://github.com/koaladlt/raycast-extensions

### Steps To Reproduce

	1.	Run npx @raycast/api@latest publish
	2.	CLI suggests to run pull-contributions
	3.	Run npx @raycast/api@latest pull-contributions
	4.	Get the error above

### Current Behaviour

➜  argy-usd git:(master) npm run publish                           

> publish
> npx @raycast/api@latest publish

wait  - validate package.json file ... /Users/manuel/Developer/argy-usd/package.json
   4:11  warning  Extension's title has to be Title Cased. Expected "Dolarcripto Ar"
  15:15  warning  Command's title has to be Title Cased. Expected "Dolarcripto Ar"
ready  - validate package.json file
ready  - validate package-lock.json
ready  - validate other lock files
ready  - validate extension icons
ready  - run ESLint
ready  - run Prettier 3.5.3
ready  - getting fork
ready  - preparing clone
error  - checking for new contributions
some contributions are available. Pull them using `npx @raycast/api@latest pull-contributions`
➜  argy-usd git:(master) npx @raycast/api@latest pull-contributions
ready  - getting fork
ready  - preparing clone
error  - pulling new contributions
failed running git Command failed: git pull origin ext/dolar-cripto-ar --ff-only
From https://github.com/koaladlt/raycast-extensions
 * branch                ext/dolar-cripto-ar -> FETCH_HEAD
fatal: Not possible to fast-forward, aborting.

From https://github.com/koaladlt/raycast-extensions
 * branch                ext/dolar-cripto-ar -> FETCH_HEAD
fatal: Not possible to fast-forward, aborting.

### Expected Behaviour

Either:
	•	Automatically handle the pull with a regular merge, or
	•	Provide an interactive option to resolve it manually, or
	•	Skip the pull step if it’s not strictly required

**Comment by remorses** [comment]
In my case I managed to solve this issue by entering the folder `/Users/morse/.config/raycast/public-extensions-fork` and running

```
git pull origin ext/{extname} --allow-unrelated-histories
```

**Comment by koaladlt** [comment]
@remorses Thank you for your comments! Even though I wasn't able to get it working with the commands you shared, deleting the `/Users/username/.config/raycast/` folder and running `@raycast/api@latest pull-contributions` fixed the issue for me!

**Comment by mathieudutour** [comment]
This should hopefully be fixed in the latest release

**Comment by remorses** [comment]
I am still getting `fatal: refusing to merge unrelated histories` executing `npx @raycast/api@latest pull-contributions`

I had to manually run `git pull origin ext/{extname} --allow-unrelated-histories` and fix a merge conflict. Maybe the fix does not work because I already had an older git repo of the extensions that does not have the git fixes?
