### ISSUE TITLE
[Ente Auth] Import secrets deletes ente_auth.txt export file, then gives no such file or directory

### ISSUE THREAD

**Issue by xela92** [raycast/extensions#20619]
### Extension

https://www.raycast.com/chkpwd/ente-auth

### Raycast Version

1.101.1

### macOS Version

15.5

### Description

Import secrets stopped working; it deletes the file it should import, then fails as the file is not found.

If I change the file flags (`chflags uchg ~/.ente/auth/exports/ente_auth.txt'`), making it immutable, import works correctly.

Thanks

```
Error: ENOENT: no such file or directory, open '/Users/xxx/.ente/auth/exports/ente_auth.txt'

w4:export.tsx:28:31

---
25:     showFailureToast(error, { title: "Export failed" });
26:   }
27: 
28:   const secrets = parseSecrets(getSecrets(EXPORT_FILE_PATH));
29:   const secretsList = secrets
30:     .map((secret) => `- ${secret.issuer.replaceAll("+", " ")}  - \`${secret.username}\`\n`)
31:     .join("");
---

hr:index.js:7:3106
    at ray-navigation-stack (<anonymous>)
Ho:index.js:7:2607
```

### Steps To Reproduce

1. Try to import ente secrets (after export via cli)
2. The import fails

### Expected Behaviour

The import should work and should not delete the file before importing.

**Comment by chkpwd** [comment]
Hey @xela92, can you tell me which settings you have selected for the Ente Auth extension?

**Comment by xela92** [comment]
Hi, here's my settings
<img width="307" height="351" alt="Image" src="https://github.com/user-attachments/assets/39e9d2a1-6903-4441-b1ba-71386a6df233" />

**Comment by chkpwd** [comment]
And can you run ``ente account list`` and send a redacted output? Specifically, I want to see your value for `ExportDir`.

**Comment by xela92** [comment]
here's the output:

```
Configured accounts: 1
====================================
Email:    *****
ID:       ****
App:       auth
ExportDir: .ente/auth/exports
====================================
```

**Comment by CatsArmy** [comment]
same here 
i referenced it in this issue as well https://github.com/raycast/extensions/issues/20890#issuecomment-3265664297

can confirm this is happening

**Comment by chkpwd** [comment]
What are the permissions when the file is first exported?  @xela92

**Comment by xela92** [comment]
@chkpwd 

`-rw-r--r--@ 1 xela92  staff  8303  9 Set 22:16 .ente/auth/exports/ente_auth.txt`

**Comment by kunalgolani** [comment]
Got the same issue

**Comment by chkpwd** [comment]
@kunalgolani @xela92 provide me a method of contact you're comfortable with (discord?) and we can troubleshoot together.

**Comment by CatsArmy** [comment]
I might have found the issue i had to fork the extenstion and mess arround with it but after forking it again and doing 2 things
```node
execSync(`${DEFAULT_CLI_PATH} *(Placeholder for the issue)*`);
```
in all instances of the code above it doesnt have ente or ente.exe or ente.bin or whatever so 
in the package.json i changed the path preferences to a Directory type which still returns a string in code but prevents user error and added ente in each instance which results in the code working(note i am on windows so i also had to move to the directory first then run the command): 
```node
execSync(`cd ${DEFAULT_CLI_PATH} && ente *(Placeholder for the issue)*`);
```
after doing all of that it finally let me export and import 

I really hope this helps fix the issue for you guys on macOS but i don't own any Apple devices so this is the best i can do to help.

**Comment by chkpwd** [comment]
Hey, thanks for finding this. Could you submit a pull request for this? @CatsArmy

**Comment by CatsArmy** [comment]
Done. @chkpwd

**Comment by xela92** [comment]
Any update on this? 🙂

**Comment by xela92** [comment]
Hi, I'm still facing the issue; every time I do ente export and then run "import secrets", the secrets file is deleted before the import completes, and triggers ENOENT: no such file and directory.

Am I missing something?

Thanks

**Comment by chkpwd** [comment]
Could you show this in action? And upload any logs. I've setup my ente auth extension identical to yours but I'm unable to reproduce this.

**Comment by xela92** [comment]
Hi,

here's the error while importing:
<img width="401" height="35" alt="Image" src="https://github.com/user-attachments/assets/74fdb156-c29d-4c01-84b8-1c247c43cc58" />

I finally decided to dig into this issue, and I think I found the root cause: when importing secrets, the extension first tries to re-export them, but the export function deletes the existing file before doing anything else! If the export then fails for any reason, the file is gone, leading to the "no such file or directory" error.

I don't understand how the import is working for you, though — it should fail every time. 

I opened a PR, check if it sounds good to you. Thank you!
