### ISSUE TITLE
[Google Chrome] search history function crashed

### ISSUE THREAD

**Issue by Lvv1337** [raycast/extensions#21561]
### Extension

https://www.raycast.com/Codely/google-chrome

### Raycast Version

1.102.7

### macOS Version

15.6.1

### Description

Error: Command failed with exit code 1: osascript -e 
        set winExists to false
        tell application "Google Chrome"
            repeat with win in every window
                if index of win is 1 then
                    set winExists to true
                    exit repeat
                end if
            end repeat

            if not winExists then
                make new window
            else
                activate
            end if

            tell window 1
                set newTab to make new tab with properties {URL:"https://langchain-ai.github.io/langgraph/concepts/low_level/#reducers"}
            end tell
        end tell
        return true

  
85:278: execution error: 未获得授权将Apple事件发送给Google Chrome。 (-1743)

        set winExists to false
        tell application "Google Chrome"
            repeat with win in every window
                if index of win is 1 then

### Steps To Reproduce

1. MacOS laptop
2. Open raycast and use search history command
3. Choose any history tab and press enter
4. Crashed

**Comment by haydencbarnes** [comment]
https://github.com/raycast/extensions/pull/21487 should fix this, it is WIP

**Comment by Lvv1337** [comment]
> [#21487](https://github.com/raycast/extensions/pull/21487) should fix this, it is WIP

Thanks, How should I execute it? I see that this extension's update date in Raycast is still a week ago. Should I wait for the plugin to be updated in Raycast, or is there an offline installation method or something? Please give me some guidance.

**Comment by haydencbarnes** [comment]
@Lvv1337, this has been merged. If you run "Check for extension updates," it should work now. Please confirm.

**Comment by Lvv1337** [comment]
Sorry, but I ran "Check for extension updates" Raycast command and the output is "You are up to date!" but the search history function still failed...

**Comment by haydencbarnes** [comment]
@karolre

**Comment by j3lte** [comment]
@Lvv1337 I checked your issue, which translates to "Unauthorized to send Apple events to Google Chrome.". When googling for the answers, someone mentioned Full Disk Access.

Can you check the following: 

> Mac System Settings > Privacy & Security > Full Disk Access > Enabled for Raycast

This should hopefully fix your issue...

**Comment by Lvv1337** [comment]
> [@Lvv1337](https://github.com/Lvv1337) I checked your issue, which translates to "Unauthorized to send Apple events to Google Chrome.". When googling for the answers, someone mentioned Full Disk Access.
> 
> Can you check the following:
> 
> > Mac System Settings > Privacy & Security > Full Disk Access > Enabled for Raycast
> 
> This should hopefully fix your issue...

Sorry, I enabled full disk access for Raycast, but the search history function still failed...

**Comment by j3lte** [comment]
@Lvv1337 Ok next up: `System Settings > Privacy & Security > Automation`. I believe Raycast should be there as well...

In the end I believe this isn't an issue with the extension, but Raycast permissions. I am basing above (next step to check) comment on [this article](https://osxdaily.com/2024/02/25/fix-not-authorized-to-send-apple-events-to-system-events-mac-error/)

**Comment by Lvv1337** [comment]
> @Lvv1337 Ok next up: `System Settings > Privacy & Security > Automation`. I believe Raycast should be there as well...
> 
> In the end I believe this isn't an issue with the extension, but Raycast permissions. I am basing above (next step to check) comment on [this article](https://osxdaily.com/2024/02/25/fix-not-authorized-to-send-apple-events-to-system-events-mac-error/)

Fixed~ I'm very grateful for your time and effort on this matter. Many thanks!❤️
