### ISSUE TITLE
The first element of List rendered from cache lacks icon and accessories

### ISSUE THREAD

**Issue by skoch13** [raycast/extensions#2402]
Raycast version: 1.38.2

## Description

The first element of the List component rendered from cache is rendered without icon and accessories, but scrolling the list down and up makes it rendered properly

## Steps To Reproduce

1. Install https://www.raycast.com/tiulpin/youtrack
2. Connect to YouTrack server and wait until list is rendered
3. Go back or to Raycast root
4. Return back to the extension

## The current behavior

The very first element is rendered without icon and accessories

## The expected behavior

All of the list rendered properly

https://user-images.githubusercontent.com/29177689/181287973-a7b43d83-a9a7-406e-b03d-4fd7d7a2599e.mov

**Comment by mathieudutour** [comment]
Could you provide a small reproducible example?

**Comment by skoch13** [comment]
Sure.

Credentials:
```
https://raycastbugtest.youtrack.cloud
perm:cm9vdA==.NDctMA==.NHklkGq56rKRXitSfPgXdT0UEyXDaz
```

STR: 

1. configure extension as shown at the screenshot
3. open the extension
4. once issues are loaded press `Backspace`
5. return back to the extension
![Screenshot2022-09-27 at 06 02 45](https://user-images.githubusercontent.com/29177689/192429195-308a06c9-0755-475e-8668-ca561977b2ac.png)

**Comment by mathieudutour** [comment]
I don't seem to be able to reproduce now, should be fixed 🎉

**Comment by skoch13** [comment]
I have to say it, but the issue still reproduces with the latest raycast api
![Screenshot2023-07-26 at 18 53 49](https://github.com/raycast/extensions/assets/29177689/1346a703-e7ce-47c3-940b-67f82ea8281b)
