### ISSUE TITLE
[raindrop.io] Cannot search bookmarks

### ISSUE THREAD

**Issue by Tapokj** [raycast/extensions#4083]
### Extension

https://www.raycast.com/lardissone/raindrop-io

### Description

I can't search across my raindrop bookmarks. I just created test token and connected to raycast. 

https://user-images.githubusercontent.com/34583186/209808514-73875b8b-97fc-4892-8dc8-146dc5590c61.mov

Here you can find short video 

### Steps To Reproduce

1. Connect raindrop to extension
2. Try to search bookmarks across your collection
3. Receive error message

**Comment by lardissone** [comment]
@Tapokj thank you for reporting. One question: is your raindrop account new? How many bookmarks you have?

I'm asking because it was reported previously and happened to users with just a few bookmarks in the account

**Comment by Tapokj** [comment]
@lardissone 

Hello! I have 221 bookmarks, account created aprox. 4-6 months ago, so account isn't totally new. I also saw issues which were created 3 days ago, and you wrote that it's edge case which caused only when you don't have a lot of bookmarks. 

And I decided to inform, that in my case it doesn't matter. Thank you for reply!

**Comment by lardissone** [comment]
@Tapokj thank you for the information, it shouldn't be related then. 

Can you please uninstall and install the extension again? I need to confirm if this may be related to some information in your raindrop account (and/or bookmarks) or something in the extension failing in some cases.

**Comment by Tapokj** [comment]
@lardissone Now I removed app from raindrop and created new with new test token, also I deleted extension and connected again. Result is the same(

**Comment by lardissone** [comment]
Thank you!
I will try creating a new raindrop account and experiment with it.

Question: do you have [groups](https://help.raindrop.io/collections/#groups) in your raindrop account?

**Comment by Tapokj** [comment]
@lardissone Oh yes, a lot! 

<img width="335" alt="Screenshot 2022-12-28 at 12 35 20" src="https://user-images.githubusercontent.com/34583186/209813081-9afa66bc-be11-49de-bd5c-8b3efc29b702.png">

**Comment by Tapokj** [comment]
Hmm, I don't know why, but now it works as expected. Without any error messages. I haven't done anything. Hmm, weird. But I suppose you need to test search behaviour deeply. Thank you for your replies and help!

**Comment by lardissone** [comment]
Oh, weird.

It may be related to some rendering edge cases.

Thank you for help me debug this!

**Comment by lardissone** [comment]
@Tapokj should be fixed now with #4085
Thanks for your help debugging it!

**Comment by lardissone** [comment]
@pernielsentikaer @Tapokj this can be closed, fixed with #4085

**Comment by pernielsentikaer** [comment]
Closing as requested 😊

**Comment by macjabeth** [comment]
I'm still seeing this issue... 🙁

![2023-01-12 at 14 03 04@2x](https://user-images.githubusercontent.com/8473052/212169394-73de6abc-97ca-436f-a4da-9989e43c288f.png)
![2023-01-12 at 14 02 41@2x](https://user-images.githubusercontent.com/8473052/212169396-a793ebbd-3a2f-4dd1-859f-e09f11428242.png)

**Comment by lardissone** [comment]
@macjabeth oh, weird. Can you provide me more details about your Raindrop account? number of collections, aprox. age of your account, number of bookmarks, etc

**Comment by macjabeth** [comment]
> @macjabeth oh, weird. Can you provide me more details about your Raindrop account? number of collections, aprox. age of your account, number of bookmarks, etc

Hey, I think the issue might've been related to me trying to use it behind a work VPN. When I used it on my personal PC, I didn't have the same issue.

The browser extension seems to search through bookmarks just fine though... so I'm not sure.

**Comment by pernielsentikaer** [comment]
That might be the case; if your work VPN blocks requests 🫤
