### ISSUE TITLE
[AWS] Unable to change profiles

### ISSUE THREAD

**Issue by altjx** [raycast/extensions#5121]
### Extension

https://www.raycast.com/Falcon/aws/

### Description

According to https://github.com/raycast/extensions/pull/3612, we should be able to select the profile when choosing the AWS command. In the original PR, you can see the profile dropdown in the top right corner:

<img width="782" alt="Screenshot 2023-03-03 at 8 01 35 AM" src="https://user-images.githubusercontent.com/4023423/222726693-00317645-adca-4e58-bec0-f3fd211ac2a9.png">

However, when I go to the CodePipeline command, I don't have this in the top right corner:

<img width="745" alt="Screenshot 2023-03-03 at 8 02 01 AM" src="https://user-images.githubusercontent.com/4023423/222726782-8a39de85-329b-4491-b695-ea3584129af2.png">

As a result, I'm unable to see anything in codepipeline in varying regions. Here's my `~/.aws/credentials` layout:

```
[default]
aws_access_key_id = XYZ
aws_secret_access_key = XYZ
region = us-east-1

[dev]
aws_access_key_id = XYZ
aws_secret_access_key = XYZ
region = us-west-2
```

I'm using Raycast 1.48.5 on macOS Ventura 13.2.1

### Steps To Reproduce

1. Bring up Raycast
2. Search for an AWS command (CodePipeline in my case)
3. Select the AWS command.

After step 3, there doesn't appear to be any profile selector in the top right corner of the Raycast window.

**Comment by JonathanWbn** [comment]
I just opened #5141 which should fix this. Could you try?

**Comment by altjx** [comment]
Hey @JonathanWbn I'm still experiencing the same issue, but I'm also not quite sure how to see if my AWS version if up-to-date.
