### ISSUE TITLE
[Todoist] Menu Bar tasks fail with `JS heap out of memory` error

### ISSUE THREAD

**Issue by MichaelHHeng** [raycast/extensions#6562]
### Extension

https://www.raycast.com/thomaslombart/todoist

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20

```

### Steps To Reproduce

Activate Menu Bar Tasks

**Comment by thomaslombart** [comment]
Do you have lots of Todoist tasks? If so, how many?

**Comment by MichaelHHeng** [comment]
Yes, i think so: 3849 completed Tasks and 674 active Tasks. 🤷‍♂️

**Comment by thomaslombart** [comment]
Thanks. I'll investigate that.

**Comment by thomaslombart** [comment]
I suspected that. I'll investigate this bug, thanks!

**Comment by thomaslombart** [comment]
Hey, so this bug is due to Raycast unable to render too many items at once. For the `home` command, it'll need an internal fix so it'll take more time. As for the menu bar, I should be able to ship a fix this week.

**Comment by thomaslombart** [comment]
Hey @MichaelHHeng, I've pushed a fix that should solve the issue in the menu bar command. The `Home` command and other commands may still be impacted because this is due to a Raycast internal bug that we like to test out for a bit more time before releasing it.

In the meantime, you should be able to search for all your tasks in the new `Search` command.

**Comment by MichaelHHeng** [comment]
Hey Thomas, thanks a lot, Search (Tasks) is working now!

Home still doesn't work as you describe. And there is an error message in Search when you search for projects and then confirm the project with "Return". Then the error message "Something went wrong" appears.

<img width="556" alt="CleanShot 2023-06-10 at 22 18 18@2x" src="https://github.com/raycast/extensions/assets/122787238/f937aaca-ed4f-43b4-bfee-2413898b73ef">

Once again, thank you for your efforts!

**Comment by thomaslombart** [comment]
Awesome. It's expected, "confirming" the project returns the project tasks and there's an issue with heap memory when using sections, which is the case for projects. It'll probably be fixed in the next Raycast release. Thanks for your patience!

**Comment by thomaslombart** [comment]
Hey @MichaelHHeng, we've shipped 1.54.0 which should fix your issue (up to a certain point). Do you still have it?
