### ISSUE TITLE
[Browser Bookmarks] Worker terminated due to reaching memory limit

### ISSUE THREAD

**Issue by sauron918** [raycast/extensions#6810]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20
```

### Steps To Reproduce

1. Activate extension

Default browser: Chrome
Amount of bookmarks ~10k

**Comment by thomaslombart** [comment]
This shouldn't happen since the number of bookmarks rendered can't be greater than 100. Could you fork the extension, change [this line](https://github.com/raycast/extensions/blob/d2b5ab88785a05d0a12881d0a0263aa97ba3729e/extensions/browser-bookmarks/src/index.tsx#L277) to 50 and let me know if it fixes the issue for you?

**Comment by sauron918** [comment]
Nope, updating the `slice` limits doesn't do the job. I hardly believe the problem relay to how many list items do we show.

Adding `console.log(process.memoryUsage())` [here](https://github.com/raycast/extensions/blob/d2b5ab88785a05d0a12881d0a0263aa97ba3729e/extensions/browser-bookmarks/src/hooks/useChromiumBookmarks.ts#L166) shows the following increase in memory usage:

<img width="831" alt="image" src="https://github.com/raycast/extensions/assets/3842386/7c1137aa-a0c2-4037-aa8d-f84e7ee51540">

**Comment by sauron918** [comment]
Just for reference:
cd ~/Library/Application\ Support/Google/Chrome/Default && du -h Bookmarks
**8.5M**		Bookmarks

**Comment by sauron918** [comment]
Any updates on this? I've significantly reduced the amount of bookmarks but still getting errors. 

I'm curious if there are some other reports about the problem or if it's just a local case.

**Comment by thomaslombart** [comment]
Hey @sauron918, it's probably linked to an internal bug in Raycast. It may get fixed in the next release, I'll let you know.

**Comment by thomaslombart** [comment]
Hi @sauron918, are you still having the bug with the 1.54.0 release?

**Comment by sauron918** [comment]
Unfortunately, yes. In Raycast v1.54.0 I still getting:

```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:399:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

when running "Search Browser Bookmarks" command.


I've tried to re-install the extension. I also tried "Clear Local Storage & Cache" action (which helps somehow till the next command run).

<img width="772" alt="image" src="https://github.com/raycast/extensions/assets/3842386/6a512cc9-cc63-40f5-9c2f-a2a918a84ba2">

**Comment by sauron918** [comment]
The problem is still actual. The only solution so far is to use an old deprecated extension which works perfectly fine

**Comment by luka-nagarro** [comment]
Same issue:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:399:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

* My bookmark size: `11.5MB`
* Raycast Version: `1.58.1`
* My Computer Chip: `Apple M1 Pro`
* MacOS Version: `Ventura 13.5.2`

**Comment by jing2si** [comment]
Same issue:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:399:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

* My bookmark size: `11.5MB`
* Raycast Version: `1.58.1`
* My Computer Chip: `Apple M1 Pro`
* MacOS Version: `Ventura 13.5.2`

**Comment by Carehls** [comment]
[Browser Bookmarks] Issue: JS heap out of memory

- 5.1M  Bookmarks
- Raycast v1.59.0
- Chip Apple M1 
- Max Memory 64 GB
- macos Ventura 13.4

**Comment by sauron918** [comment]
Probably you shouldn't deprecate the old version of extension while bug is still opened.

<img width="785" alt="image" src="https://github.com/raycast/extensions/assets/3842386/baaa90fe-f041-415a-a6e6-5b58718d478f">

**Comment by thomaslombart** [comment]
We indeed overlooked this issue, sorry about that. Part of it is because we maintain a growing list of extensions (Asana, Google Workspace, Linear, GitHub, Jira, Zoom, Notion, Browser Bookmarks), which makes it challenging to stay on top of all issues. Another part is our inability to reproduce bugs, which ultimately makes them harder to fix. The extensions are open source because we want to give back to the community, allowing everyone to have enough room to improve them. Feel free to also take a look at them and submit a PR, it'll be greatly appreciated and we can help you in the process 😊

**Comment by sauron918** [comment]
up

**Comment by thomaslombart** [comment]
FYI, we are working internally on a way to reduce out-of-memory errors for various extensions. We don't have a timeline for that yet, but hopefully, we will soon have tools to fix this issue 🙂

**Comment by binbjz** [comment]
I sincerely hope that our team can resolve this issue as soon as possible. Actions like searching for bookmarks and opening searched bookmarks through a browser are regular operations when using Raycast. Such routine operations should not be crashing so frequently; this feature is almost unusable.

**Comment by binbjz** [comment]
> I sincerely hope that our team can resolve this issue as soon as possible. Actions like searching for bookmarks and opening searched bookmarks through a browser are regular operations when using Raycast. Such routine operations should not be crashing so frequently; this feature is almost unusable.

$ cd ~/Library/Application\ Support/Google/Chrome/Default && du -hs Bookmarks
3.5M	Bookmarks

**Comment by binbjz** [comment]
> > I sincerely hope that our team can resolve this issue as soon as possible. Actions like searching for bookmarks and opening searched bookmarks through a browser are regular operations when using Raycast. Such routine operations should not be crashing so frequently; this feature is almost unusable.
> 
> $ cd ~/Library/Application\ Support/Google/Chrome/Default && du -hs Bookmarks 3.5M Bookmarks

I have installed "Google Chrome" to replace "Browser Bookmarks"。

**Comment by chrgue** [comment]
I am not 100% sure if it is related but when I confirm to open a bookmark it is so slow. It takes sometimes until 10 seconds until it will be opened.
