### ISSUE TITLE
Field error not displaying in dynamic form

### ISSUE THREAD

**Issue by canac** [raycast/extensions#7016]
### Description

I believe I've found a bug in the API with forms when the number of form elements changes. Below is a reproduction. When you type one character into the error input, the error doesn't appear at first until you type a second character. It appears that adding the `Form.Description` element dynamically interferes with the error prop displaying correctly.

### Steps To Reproduce

1. macOS v12.6.6
2. Raycast v1.53.2

# Reproduction

```ts
const [error, setError] = useState("");

return (
  <Form>
    {error && <Form.Description title="Summary" text={error} />}
    <Form.TextField
      id="error1"
      title="Error 1"
      value={error}
      onChange={setError}
    />
    <Form.TextField
      id="error2"
      title="Error 2"
      value={error}
      onChange={setError}
      error={error}
    />
  </Form>
);
```

### Current Behaviour

Typing one character in the error box does not show the error next to the "error2" field until you type a second character.

### Expected Behaviour

Typing one character in the error box should show the error next to the "error2" field, even though the `Form.Description` element is added.

**Comment by pernielsentikaer** [comment]
Thanks for flagging this, should be fixed in the next release 🙂

**Comment by canac** [comment]
I'm still seeing this issue after updating to v1.53.3. Did the bug fix make it into that release?

**Comment by canac** [comment]
Still appears to be broken in v1.53.4.

**Comment by canac** [comment]
This seems to work now in v1.54.0. Thanks for the fix!
