### ISSUE TITLE
[Asana] unable to refresh tokens

### ISSUE THREAD

**Issue by paulminors** [raycast/extensions#8139]
### Extension

https://www.raycast.com/raycast/asana

#### Error:
```
Error: Authentication error: unable to refresh tokens

Que:oauth.ts:64:10

---
61: 
62:     return tokenResponse
```

### Steps To Reproduce

I tried creating a task but Raycast couldn't access my Asana account

**Comment by mathieudutour** [comment]
I published an update of the Asana extension which should give us more info about the error. Could you run the `Check for extension updates` command and try again?

**Comment by paulminors** [comment]
Hi Mathieu,

Thanks for the response.

I ran that command, but I’m still having the same issue I’m afraid:

￼

Thanks,
--
Paul Minors

**Comment by mathieudutour** [comment]
Isn't there more information in the error message?

**Comment by paulminors** [comment]
That’s all I see when I try to run the command.Thanks,--Paul MinorsOn 1/09/2023, at 8:11 PM, Mathieu Dutour ***@***.***> wrote:﻿
Isn't there more information in the error message?

**Comment by paulminors** [comment]
Hi Mathieu,

Any update on how I can fix this?

Thanks,
--
Paul Minors

**Comment by thomaslombart** [comment]
@paulminors Are you still getting the issue? We shipped an update a few weeks ago that would fix some authentication issues.

**Comment by paulminors** [comment]
Thanks for checking. It’s working again now 😀 Thanks,--Paul MinorsOn 27/10/2023, at 8:24 PM, Thomas Lombart ***@***.***> wrote:﻿
@paulminors Are you still getting the issue? We shipped an update a few weeks ago that would fix some authentication issues.
