### ISSUE TITLE
[Reclaim] Default task settings: visibility - is not respected

### ISSUE THREAD

**Issue by dejarno** [raycast/extensions#8838]
### Extension

https://www.raycast.com/reclaim-ai/reclaim-ai

### Description

When a task is created through the command "Create Task" the visibility is set to private.
Expected result is that the default visibility set in the settings of Reclaim is respected.

### Steps To Reproduce

Before starting make sure the following setting is set:
Reclaim.ai > Settings > General > Default Task Settings > Visibility > Use my default calendar privacy settings
And that your Google Calendar is set to share event details by default.

1. Open Recast
3. Create Task (Reclaim)
4. Fill in a title
5. Submit form

### Current Behaviour

Task gets created, visibility is set to private

### Expected Behaviour

Task gets created, visibility is set according to the default value

**Comment by dejarno** [comment]
Quick look in the code revealed the issue:

Hardcoding the default to true [here](https://github.com/raycast/extensions/blob/0b3b0d885acd4e4aeac86ae0d0fcfe7f90a52980/extensions/reclaim-ai/src/hooks/useTask.tsx#L21C9-L21C29)
Not getting the default setting [here](https://github.com/raycast/extensions/blob/0b3b0d885acd4e4aeac86ae0d0fcfe7f90a52980/extensions/reclaim-ai/src/task-form.tsx#L36C1-L36C1)

**Comment by lightbody** [comment]
Thank you for raising this. We'll get it fixed soon!

**Comment by maximilianzuern** [comment]
Already fixed by PR #9218.
@raycastbot close this issue

**Comment by masgharneya** [comment]
Looks like this issue is still present, but instead of always defaulting to private, it always defaults to public.

**Steps to reproduce:**
- Set your default task visibility to private
- Create a task through Raycast

**Current Behaviour**
Task gets created, visibility is set to public

**Expected Behaviour**
Task gets created, visibility is set according to the default value
